# Generated by Django 3.2.3 on 2022-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre ')),
                ('descripcion', models.TextField(max_length=220, verbose_name='descripcion ')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre ')),
                ('categoria', models.CharField(max_length=200, verbose_name='categoria ')),
                ('descripcion', models.TextField(max_length=220, verbose_name='descripcion ')),
                ('imagen', models.ImageField(null=True, upload_to='ImgRepuestos')),
                ('cantidad', models.IntegerField(verbose_name='stock disponible: ')),
                ('precio', models.IntegerField(verbose_name='precio $ ')),
            ],
        ),
    ]
